### ISSUE TITLE
JsonSyntaxException with certain servers

### ISSUE THREAD

**Issue by ghost** [jamietech/MinecraftServerPing#8]
I'm getting this exception when getting the status of certain servers:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 17 path $.description
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
        at com.google.gson.Gson.fromJson(Gson.java:810)
        at com.google.gson.Gson.fromJson(Gson.java:775)
        at com.google.gson.Gson.fromJson(Gson.java:724)
        at com.google.gson.Gson.fromJson(Gson.java:696)
        at x.testdiscord.mcping.MinecraftPing.getPing(MinecraftPing.java:127)
        at x.testdiscord.MessageListener.checkMcServer(MessageListener.java:170)
        at x.testdiscord.MessageListener.lambda$parseCommand$0(MessageListener.java:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 17 path $.description
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
        ... 16 more
```

Here's the JSON response of one server that runs into this issue (Atomixprison.net):
```
{"description":"▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦≣§b §lAtomix Prison §r≣▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦▦\n┅ §aJoin the new Community!§r ┅ §c1.8§f/§c1.9§f/§c1.10§f/§c1.11§r ►","players":{"max":60,"online":1,"sample":[{"id":"6ce3fd84-97b4-4175-87d6-5ccd04a40c14","name":"CM_lectric"}]},"version":{"name":"Spigot 1.8.8","protocol":47},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAaxElEQVR42tVbB1hWx9KOmqiJNzfV\nqDcSsaIiKiioiCiKvSNFUFOMMcn9k5hYEnshFhQLWBAFUURFsYCiFAUUREGxC1GKBRDp0nt5/5n9\n9sNPAgjcm/vf/zzPPH4eztndmZ15553dPW+88dddb5GMJtnYpNmbQe9raWWomUyFxoKf0XezDbS3\nbYb+SXeSo+J3382b0P23heBn3tPUTG/SpEkgvbuBZJRs6//NNYjErpV6h8Su33+LwSeOYcLjaExH\nOb4AMFtFvpSieo+fmY5SjI/5A4OOuKHLN3PQSk0tkdskGfjfrPg4kgsdzM1g6HkS5sW5QqGvSGaQ\nmKMQpiXZmFb4ok7hZ8xRJN5RGsWsMBtDPI5BbdpUUB/nSSb8NymuS+LbceZMjLt7u2rQFiiTSmW+\nVunahd4teiG8R2nMsbdvotOsWUpDDPi/Vt62jdEwjL4aWuW+02gGTQoy/gWlaxbRZmmO6ONrkjHh\nV9BmuBEbYgtJk/+04n2pyyjdndtFDH9VpXgDZ7soC6bFWQ00RKbo6yuJH3oOO/FGsyYPaEz9/1PK\nz3y3hwYm3L+Hb0RsFzdoxvlZi7JcmNK7BjSjg8jNJwvgK4JJfnqD2uG+59K7E/+Iwt979WRv+OKv\nVv7XduPHYEZZiXB5E47Rhsw6PTujvBDGxXnQOXYIn9PszXHcDYP9zjBIT8JMVJIRMhrUHo+BvWFm\nZRnaTRrPRljyVym/+rOZlqKzWSRTC9IbHMemBGhjCRwHHNiHIDc34NlzIC0dD86ew2j7LRiS+wIW\npXkNbncqec4sCb7qsz9nI6z/dyu/SG26meiA09PU/IYrbyIH2fZqENycnFD9unXSE+0O7aPsQXjS\nCBDlCbEiD2KA7PDlTDbC8n+X8jPajDauyueNUp4GN5Pe1XwWj0nrfgcyX6Cma4W9PdqHh8CysUbI\nZyNUiIlqqwiHfxkTev9No6uYuVmNVj6DlC+HTloSxluvBBKeCWWL8vNpqIqroqKiygi/kIE637om\nDGbSiDBThgPLuz26sRF6N1b5pk2aNU2elPBIzH5jYp7FoiQHRhUl0LPbRMonISk2FmNnfwnXrVuR\nHxuH8uQUXDx8BNPmfoOLAQFAaTlm2KyDdkoCrCpLGgayKuHAY55MY2cdGssTDugd3i/SzNRGsjmR\n8hiYPN1x/fwFICUNuiuX4bPr4Riwewe+W7wYPy9fASMqhjoRmWq/agniQi6jlLxEy3E7JnAoNLJv\nHjOPnXUgXQ7WV2mlpQa1GTkCc5iHl+Y3ahZYLCnl9Xr+BAt2Owj3nrdhHTQePxBANYWk/5OH6PvH\nHYyjYOB7ejkZGDn/Z6CkFEePe0D9WrDAnUb1T+/w2FmHtmNHsREG11d5vh5OfPZY0M76khwuYkyJ\n2JiSy/O/PHPm9L6Guyue37yN+Cth6HLQSdxTxjYXPRZEZpgRcj8ctx18T8FjtyOQmo5hex0whg1Q\npGjfrDwf5pX1K6oUmSdD6DA5NRFUXse9Nublv1ZdfvxeuI9JXTSVLGyBEmJwwGhKP/0ynkEnNR79\n0hKhkxKPoaScWupTzN+1EygoxpwDLuifm15nnjej/owJMA3sNgPPU+Dh6YnWt0Ixgvrg9vs8fYhe\n0XfF7xFUMpsJBlkhw6RmL2EdWBeNRb+wF1i9dvabtWzxdGpWqmBlNbkec3GL0lzRuVbMffQ57o6p\nbq5Y6XUKG/19sfGCPzb6nMOP57wx2HoV0p8+RVlyKtTWW6NXCc02vWdFYlpVO2SKesBS0GpgCEnz\njWsRdSkYyMnFaMoKX5w8gXXnzmKHvx92079LPU/Byu0AdI8eQo8bVwWVtmIqXZO3MvtkI+W9QLN3\n3kmsTfk35W/zbj//oJj9oppn3aosHyMJ1bsdOYg1RGPjIm4AsY+IydxGfmAQ8gIuIvdCAEouX3kl\n31++GobZRH31Dh9C1wu+MCjMEvHN6W4EDV4jJAA6Bw9ghuMuePn7c25UvEhGqLh2HTl+/sgPvkz9\n3AHu3QcexiDlzl3YOTsTYDpgcG4mtVVaoxFYFxUvmFKT6yvdP3zckwf4vBbgMaOGRpOL9nF1RsDx\nE2J8jy5exEoiMJMorRmTmxu77oPxoYMYtWkDwkJDxTNx1yOQHhYGUMrLffAQ+5z3wWy7Pbp5e6Kz\ntxfGkWF27XVCMhkRSc+RQc8GeBwHKiuRmpAIq532MHLdjxFu1D49a7ZxI+Zv2YLrp0+L9mODgzHI\n1gaDC7IxvaYQI10YX8YnxrIBwqsbQDn7fduMMBIlpmktjXC8awScg8+Jk6LjJWt/R8cttuhxMxzD\nK4sxke5x6uJKr931EGwn9C9+/ATG1qvRb8N6zFq/FjeuX1fMbGqayPt+fr4oefJU3Ep4/BjfbrRB\nf3s7qC/7DbfIoyL8z0PN/wymctVHMo7EiNC9N2WPDjvsMfMXyhq5uYgJC0fPIwdgUlvWoLBlbtBm\nlDEboaOqAVrKf9fqHXAS6agmN+I4NSjKwVfOe4HiMjiQ673v7SGwgDn4tCK5gsPph+4NOHMCaTdv\nIcDbG52uBAmv+uhRDN6YNAHhPr4v+W+ltEd0DD6cbo7md26KZzUzE7HMzg5llEHGEM5MUFWM+rIk\nd2csaRcRirlLl4g2Nh05jF6UWs3KC2rkJKzbAPIi0nWpqgFaMA40efPNGxMJxUXerQFNOf30irsP\newKkiqgHGMmuzrNdHSvo/8MqimF16ADFxxOsP++HbmT9TgH+sKBYDb5zR4SCn+MemC1diom/LoKr\njQ1NfyJuE0uctXcPPjt9Ev2obUuPIwD1ZU0A2zctHmZlOdW8MkN4m5azIzIIc8LIuzRDAxQFVQ06\nsG6TM5PQtHnz69XDoE9rQwNheVPKtTUagICqN6Wgg4TET8k1+wf6ipConn44V/dOjMaao+5ARhaM\nHHbgoz274OJ2kNJhoVBo/upV6LF+PbQT4qCbnAiN7XawWLQQ8eTuyMjEiWPHoE0o38Hmd1Eue10M\ngsa1EJV1xleV6n7RD4FepxF19y60iTyZ12IA07I8oeMnRkPZCz5WNcA3PZb8KlykNtbFHtA75h6c\nKQ2lEKIPCvARrv5nQ5VAM/IWtrgdEm7pQwAVf59QOzcfe7Zugc7yJdAkzDARoVMiVoLYkNpPYtDF\neg2WrFwBPE1A6fPnOH3eX7Thf/48tChLTK+hP77Xx8cLsaFXcPvWLfSmcKvNAzjtMjPUJDpePRs4\nDD55VLG2VxvTI3anm/UcC13JtSkuLbxOUAhUvlK2MvNiC3969SJ2E9IrrxTK6eN/ngd1D3fKIpBh\nlvFKfFpRdmGjdL0UiEHzfkTI/v1V74eRZ6ifOS5ifppKUcYKjad7I90U4XaMDNX9RigZoLRWPVhH\nA8InxjxVDDg/hmZtZh0GYBlLfzemlMS5eMuZ0+iS8ABWFUVVSnCq6f48ARMoBabFxQFlZdi9yRad\nVy9H/7TnQnFmezUvnmYKo3AbhqUFULNZj5+//yeKnyWhjFD+f+y2ov3dCAWJkkY3L8lFn9xUfO20\nh1A0Q0xOP5ok09LaqTLrODb6HhvAU2mA9m/9/d3IKVnJioWIOgzAnWv4eok0+CLyD2gfdRPpiZVn\n5bpFR2HcqmUooDKXL99jHmi3Y6vg81YUv/WpK/gZy8oiwRjbUiW3etlyhRukZ2DumpVQDwsRLs5G\n4PF2Jc+4TR7GGUf7oLMAxbqKJ6bOPAEtWre+pTRA//d7a6Wx25hTLq9rcGYUBvrFuZiy1poYWh5s\nyeLqD26LuOoaeRuzfl8NvMh+ucLj6opuCTEi1htW1lIhRUWVPr032X4rMu5FVrW5lHhCx0sBYib7\n5aRjlv02kUqtqeboFnNXsYZQlw6EZZZkhA91+6WR7m+zAYw+MRxSINyzPO+1a/Js9S7H3eB30E0A\n20DHHWh23hdfkdujoAhXLlzAnAULUJmVhZ0EYr2pgDGvyG9UOT2kLBffEQfIJoa4xNYWhw64CiOs\nJzbYKtAP7VwckBIVhcRrEei5Z4fwRlVsqdEA1CYbr/UwwwLS/UM2wIS2o4xL+Sb/8XWDMpcrPLq/\nLkBR3GNEREbily2biByV4Ib3WbRxsEP77VuRT5nCJTAAWrGRIoM02ABUIg8mTvHD8aMoCw3DsP1O\neGPnVjgT5eZVI2viFO6UkbhWmEaZQyczGVblRa9t16xUYYC2Y0YWk+5t2QCz1b+cJSgwd1qfGGVv\n6Ukpcc6aVQR05WJW7ty8CY1tmzCYFzsC/ZHpdwEb/HyoPE6AWUlOIw2Qie+OkKfduotFIUHQpbbb\nOzvAxdW1KiQ2OTuhY/glgU/1WrsgEGZdO82ZzUDYT6z6fmoyuVKQoHoO1KL4BfTo+VG7tgPxiWIg\n9o6OeDtUEZujqVLM9PGHdXAg9PLTYdqY/UClAdzJADfv4IczniLltc1KwiRJffmasWMbuuQmYyYD\nZz1WjlhH1vUzC7NK0r07G2BS6yEGEgPy6+UBTIC6nz0JX19flKWkUEV4SQDRTzu2o83TWEy8EYZc\n8oC1FwOhm5NMdDnrX/AAYpDhEfj1TgQ+ITcfs9UWGVQ8xRPxyYx7hBii1lpUw4girB5Aa0ZskHX9\nZJhhvpINTmptMDhXGKAeYMUoq/EkGiscd4sZWOywC22/n4tr53xEOMw+7Ip/LJqPIgImm8vB6J/d\neAPok0LzTnmglHiHjs1a9LO3BZ4nI51SXqf5P2HCb4uA8gocPXIE7S8rvO91XsBAz7p+bKCfowRB\n41Yd1ZOYJ9fEtV+VDGHpAVR8FD+Jx43zF9DpxGEMpOnvROVrIGcGuq4GBqIyOxe/nDsDveLGnREw\nITEoz8U3x46gMjkV/lwn5Obh+aUQaP82HwMolXUI8sF+ewrDkjJM2WGHIUX5RLTqXi/kdM/V4t+6\ndH6kXAnTa9Ks2e0JCbEKqlnXKi9VeV2j78CeLI68QkyxtYFuQTaBShlGkHS2Xgm339dWxecCQmq1\n+Ici5hq6gzyDBqpJITCdeACyc0R79096ojfVLPq5WfiCqPMoriGI1yM+AaEXAqB+/kyt1awqmZuU\n/ARNW7QIVhIhLZKzw4L8FQcc6lprp78Pdj+IoofRCKb47+J3WnSo4PLFgvF9Rsxvybx5KKf09Oze\nfQxZZ40uVOiINT+xyFq3N3AcC5KTn43uthsQzvhCl7uDAzqtWQHDskLFrpHcAepyNQibOTWmZ8KC\naoIRFXUTIdZxeGgQZwBnpQE0SXZpU+6uqxrkOn8g5dB/HuZd3WT8z8nj6EeDNZNL1EySphOIspHa\nOu3Cvu07xMALomPx3cb1UKca31isAVbUvG4njFiKSbyRcjkIEzduwOOwcNFGNHEKDTLGcEGpVc4j\nkIeMZIUcKAwePYWjzzl0fxJFWFZQ60o269hv9w42wM+qZ3zmq38+Q2wqTqtpKbyAZ6UMHR5HYQ3X\n9ZlZGLt9G7pTjM5gjl+1Z5gpaGYvIj/L7exfrvoQQzx+7Ch0N28SlJmrPksUCkVY2HBcw/ckT+lN\nmWSbyz5FepWLql6nPNGTylyFt2VWVZ4ziCoP4vJ203ogMQnePj5oF+xfe8gRHokt9C/FFrqB0gDD\nSSa/o9Y+y5xmoKZS0owQeTQp1nfvbkRfU6zphQQEwIDorwFVeaoMzJzycV8ywOp9zmJxY/4eR3yx\nQhGnvOqzhDi75l5HaCY9FbW8cPesNHRz3Y9vt25GXtQfQFoGVu/ehYHzfkAJpVnvoCD0unaZxlbx\nEo9K82CUnQ4d+83w8vQUY+K0OJrS5IBcmojSghoBkOUdNbV0ZR2gPN7GXhA0IjxYwQirhYEZdax5\n3hu+Hh6vbGenX7oMQ8rB41UGxkRjENXsc50cgWs3YHr6FN65ehlGv8yDPzO4wmJEBlM/m23R8/gx\ndPZwhykVOCGEKSirwC0vL0yc/ws63o5AL4/DKL4ShoNUU/T846ZYlVL2w1trem77EHvG+5UxxVwI\npKrQSdYFr3ox6zbiWgjP/lHVzaCx0gA23Sl/zxF7ApmvxL4RuZolUU5eqal+rT/qjl7PYgTBUL7D\nqXI4eUtF+HWxkaGTkybiv6vnCUxcsxq5ySni3dAL5+HLS9u8VEYpbva2LehORhlckkeVYBl+2k+h\nEB2H2QRug4tzhAsrFmizMYDC7Z/7aExZ2X8a0yrCqT6p8XKLTrk3oFgNknsDn6uuiPNR1DEk01q2\na5vH210WlaWvGGAo3Zux2wEvrkf8qbMfDx1Ez7IcKImUOQEQo7Pm5UCEU50ef/0GPjjkDJ0XmeTG\nYei6eCHCA4P+1E5qTAx60QR0DbkE3cxUtPQ6imAKs6LYOOj5eIlw4fZZOJXxoqmVi5PYR6h+2Xgc\ng+azWJiqLKKyTqxby7ZtmAB9JGe/mSBCJFOlF5zWP+X+p6VxXmTof+QADqxcLdheZeXLzlzOnoXa\nvt3oEXZZgF+v2HvoHf8Yb+/fA28/P7HTu4Jm8gcCtpvBlNLy8lESEws7a2t8u2IF5ixfjsWLFyPh\nyhXxt3sUHksPH8aPDjuFZ8TfvYt228kzYmNE21pxUehxJRhqu7dj57FjVeMol4OKPuUFoz07Ma6i\ntKq4Uy6J63sd49l3krP/jjIEjJgOSzD89oP+OiJXqq6tTyeXNC7Mgf76tbBf+CvO7XXCjrXr4ONK\nGSG/EDkEXOeCLmI/KegUeAH7LgXB/xIpW17+0lL5BYil8thu5y5MXb0Kmu6H0S8mCgMex6CHrzeG\nrFoJ6y1bcPPcOUL0Z6/M6E2qNPcQDjgFBVAfwThDDDTtxi1Bg+/Q7+OUckMPHcLJjbYwXr4M+inP\nYKXCB8zKCkT8fzRAF/J0aRMJgsIAQ0jGk5jJP4YYBvq84gVKZjaGkLePlweMjh5E36NHoEP59Kd1\na+FPaSqRipOC0KvA7Xvi3yiirocc9yAjKQklFKfzqWZQJ+lBOX4IxbOV2NktIYAtFCEzhuh0z4ir\n6LTfGRNXrcBD4vt8nff0wm0CyHxu+14kSglXki6HimXwVRtsMHzDOui7umDUtq3oSxR9aE6GPG6X\n/srsDws+z8r7ytl/j6S5kgoPVGKA9IK572n2FF5gUf6yxBRVYHmeWI+bKnd4+d++j6KgSTHanxDb\ncN8ejHPaDUOKTV0qXz/ctBb7iMFVPHiIPnRvlMj/lYqyWzXT8G/iH3xKnBmjGlWA93z8EHvlKtRW\nLYXOaS8YUNsTSEGjvbvQ320/tE4fh1bEFWqzSFSnvGVmJs4oF74MX2rXvLxQzP57Wr0gvb2pNEDV\nEXxeFBjBXIBkusQC737E5r5VHoas7SCzOCOgWNfnzieJmYQ8+UlW53285UuBJwlw8TyFrnfCyJMq\na2WbXGtoPYvDQl7lpXT5g+0m9H6hWE2eIttW7j1OF1IuMkJtY1Qek+nv4qia+trK+G+mWgsYyiPo\nZjIcJjRr0SJnWmaKZFWNPR0GdDp3Eif3uYilq8FEWUfWtJ0mt7nYo7o5OyDnYQxSKca7uypPlGQ0\n6mie2OUmktWsZYtc0kmD5AOZAVqo7Ii/0U2GwWiZDWbIjx5WtjYyFPHDodCYQZhT7TC8tBD6vy0U\nx+P8iKq2DTxbwwaH4hxh+xuh2OniImL/eyJH2klPiCYXNe5wFrk+5/1PjMWJ8h/kJnAHkr9X/wKF\nb2rL+JgovaAqFHquXiZC4U9x2wAv0LhzDQt/+1WsGi3atQOf3o0QsW5RWQDzslxhEPWYSHxls14o\nf4Y8Rv30MfFMgw1PY+Sx8pg1f1/Jyp+SMd+V5JPq7q+MiR4k+hIMTUgsJSZwwRClf9xdxJIolBp8\nYitDuHEHyhwuW7aKUFiw0x7qBw+gd+Jj6KQ/QwdiiF/zynJRCf4g8Otmu15kBfPi7AYrz7mfxzr4\nlAcrHyXPAnQhUSd5X7kbrmqAj+RDOjILTJJewKEwUmJD8oiLAeJ4vDg600AjWJAiDJBqO+3gtHEj\nEZ4CRIaGYglViAsOuSGE+AExGVz1OI4+q5bBsChXVHomDTyJzmPjMQ4PEikvVU5gR1ny80S3UjkQ\nUnX9jaSd9IJB0gsYCyxIZpEMJTEleTEyNFh6QnaDBzedagU2Qhc3F8ybvwDPLoUARJNxNRwvqO63\nWbUGPam6HEpVHB+tbZDryzTKYxtFhReNNUvWOJ3lhxQdJAC+An6qJ0Q+lC7Sl2SYnHVTiQWzJFni\nsEgf5n1axBdz/oYOUnm6rM/NcGhTRpi81wHT9jthIP3uGegvDGRV2fAPMHgsPCajc954o0mTDBnG\n3WRYc+y3UZn9JjV939dKPsQv6cn6YLIKIM6SqZI9I7qf3VaBsDMbeoBaHouzlLmct8pHUimtJFam\nDcSYqTJ78Fj4XBGNLUamcU3pub1481eCYI2zr6yJW0iAaC9f0pdpkQ8RmKsYYYTEBT/1z2fCoiBX\ndG5KDPGv+FCqzr0J6pP7tsjPQUfFCo+/9N7+cgI5s3WSa/9vV0f+6ucEm8n08JEMhT5yxsdJd1I1\nwgTJGza9/Vn7wqGnTlZ9BNmoD6ca8cGU8mNLw5Mn8Hb7Twt5LFJxQ1ne60pvZq9+V3p509edE35L\nAuInEjz6SYuqGsFSZgdzGSozSQLVJk/GmIhrVYbgLWiTwsx/q+Lc5ldS8THhV9Ge+uRVLHn8VVuO\nc7ScHAb0T1Vcv1m9vg+QFdLfZcroJq1qJONK1RMspfIj5Sns30gi1C2nY2RIkIjLr+VHC2aVBY3+\ngJLfnSXb4jaNgwPBX6ZyX7JPfTlJU+XMD5LxryZRX+n6Tep7VL6ZtBhb7h9y81C3DiPMkL+HSA7B\nX2xd+lhXt1jbdiPG3r8lqj/lzH0uzwfxKQ3eheLlaxb+zfdmyGeUX4nyu2Mjb0N780Z8rKdbQm3z\nZsZiOR59WcFOkRMxSOJXBxnK79SG+vUxQksVI2hIT1CGwxSV7GBZLSyGSmPMJnHkmfqgb5/8zt/M\nge4eBwy/eAETnsbAJDuNCqJskQ1ERijKEff4b/yM7p5d6DL3G/C71MYNkj0kX8u2DaXiphKPRtSi\n/FuN/VJEeXi6pcwM/5DhoCM7Hy3Z4rRq3qA0hKU0lL4cHH+4tJrElSSgafMWkW+3aZvYSl095aOB\neoUsrTp2TGlJ95o2bx7Jz8hn15B8KdvQl8TGQvY5RfZhJBdx2O0/k4jfqj6gp7z+F4777aDXBylC\nAAAAAElFTkSuQmCC"}
```

Dinnerbone's [mcstatus](https://dinnerbone.com/minecraft/tools/status/) doesn't run into any issues with this or other affected servers.

**Comment by lucaazalim** [comment]
As I can see, this problem occurs when you try to retrieve MOTD from servers that use JSON based MOTDs. I had this same problem some weeks ago but I couldn't solve it yet.

**Comment by jamietech** [comment]
Which charset are you running the query with?

**Comment by ghost** [comment]
UTF-8.

**Comment by clienthax** [comment]
This is because its trying to parse it to a Discription, when its a string in older servers

**Comment by ghost** [comment]
Is there a solution to this? This renders many servers impossible to ping with this utility.

**Comment by lululu9** [comment]
it seems i have the same problem with a thermos server ive made, please is there a workaround or something to edit in your code in order to make it work ?

**Comment by lucaazalim** [comment]
> it seems i have the same problem with a thermos server ive made, please is there a workaround or something to edit in your code in order to make it work ?

You may want to test my version: https://github.com/lucaazalim/minecraft-server-ping
